### ISSUE TITLE
Falied to deploy smart contract

### ISSUE THREAD

**Issue by omkarsunku** [Concordium/concordium-contracts-common#27]
Hi there,

**Bug Description**
I am trying deploy one of the smart contracts which is piggy_bank_part1. I can able to successfully build smart contracts. But when I try to deploy a smart contract it is throwing an error as shown below:
--------------------------------------------------------------------------------------------
Using default energy amount of 3081316 NRG.
Deploy the module './target/wasm32-unknown-unknown/debug/piggy_bank_part1.wasm'.
Allowing up to 3081316 NRG to be spent as transaction fee.
Confirm [yN]: y
y
Deploying module...
concordium-client: user error (Cannot connect to GRPC server.)
--------------------------------------------------------------------------------------------
Can any help me out the reason for deployment failure?

Thanks

**Comment by abizjak** [comment]
This question would be better suited for the support forum https://support.concordium.software/

To answer though, the issue seems to be that you are not running a node or your concordium-client cannot access the node. 

1. If you are not running a node then start a node.
2. If you are running a node, try to use explicit `--grpc-ip` and `--grpc-port` flags to `concordium-client`, e.g., `--grpc-ip 127.0.0.1 --grpc-port 10000` or some other values if you have a custom configuration.

I will close this issue since it is off-topic for this repository. If you need further assistance I suggest opening an issue on the linked support forum.
